astanin/python-tabulate

- .circleci/config.yml
- .pre-commit-config.yaml
- CHANGELOG
- README.md
- benchmark.py
- setup.py
- tabulate.py
- test/common.py
- test/test_api.py
- test/test_cli.py
- test/test_input.py
- test/test_internal.py
- test/test_output.py
- test/test_regression.py
- tox.ini
This should make very easy to enable additional linters without having
to change CI jobs or the way user lints.
Configuration is mostly copied from tox project itself, with few
removals.
Related: #3
> Enable flake8 linting via pre-commit

- tabulate.py
- test/test_regression.py
Check that tablefmt is not a TableFormat object before checking if it is
multiline.  If it is a custom user-specified TableFormat, leave it
alone.
> Fixes #20 - allow custom user specified TableFormats

- README.md
- tabulate.py
- test/test_output.py
Usage:
```python
from tabulate import tabulate
tabulate(data, output='html')
```
To access the raw HTML string in Jupyter:
```python
from tabulate import tabulate
tabulate(data, output='html').str
```
IDK if this needs to be in the docs? I added notes in the README there
> ENH: return a wrapped str w/ a _repr_html_ so that Jupyter displays the html

- README.md
closes #29 
Have added absolute path so that link works when viewing project on PyPI
> Put absolute path of CHANGELOG

- README.md
- tabulate.py
- test/test_output.py
This adds a new `pretty` default TableFormat to make it easy to convert
legacy code using the PrettyTables library over to using tabulate.
It does not provide 100% output compatibility, but it does address many
of the differences between PrettyTable's output and the closest existing
one of psql. This will help minimize the impact in unit tests and
expected user output for projects to make the switch.
> Add `pretty` format to behave like PrettyTable

- tox.ini
Not passing these vars can prevent testing tools from running on systems
that do have http proxies.
> Added proxy related vars to passenv

- tabulate.py
- tox.ini
> Fix DeprecationWarning on Python 3.10

- tabulate.py
- test/test_output.py
> Fix a bug that header shifts wrongly when do tabulate(headers='keys', showindex=False) for pandas DataFrame with named index

- tabulate.py
This strips terminal hyperlinks from text when stripping invisible characters. Without doing this, the wcwidth.wcswidth() function returns `-1` and the column widths aren't correct.
The escape sequence for hyperlinks is described here:
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#the-escape-sequence
```python3
import tabulate
print(tabulate.tabulate((
['foo', 'This is a link', 'bar'],
['bar', 'This is also a link', 'baz'])))
print(tabulate.tabulate((
['foo', '\x1B]8;;https://example.com\x1B\\This is a link\x1B]8;;\x1B\\', 'bar'],
['bar', '\x1B]8;;https://github.com/astanin/python-tabulate\x1B\\This is also a link\x1B]8;;\x1B\\', 'baz'])))
```
Before this PR
```
---  -------------------  ---
foo  This is a link       bar
bar  This is also a link  baz
--- …
```
> Strip hyperlinks from text

- tabulate.py
Current version(0.8.8) breaks when each line of multi-line item contains different number of full-width character. For example,
```
import tabulate
l1 = [
["가나\n가ab", "가나", "가나"]
]
l2 = [
["가나\n가나", "가나", "가나"]
]
print(tabulate.tabulate(l1, tablefmt="fancy_grid"))
print(tabulate.tabulate(l2, tablefmt="fancy_grid"))
```
results in
This pull request fixes this behavior.
> wide character support in multi-line item

- tabulate.py
With the `floatfmt=',.2f'`, the tabulate is not recognizing the number as a number.  I believe the commas is an issue for the number detection code.
An illustrative example:
```
>>> stuff={"first": ["c1r1", "c1r2"], "second": [14502.05, 105]}
>>> print(tabulate(stuff, tablefmt="grid", floatfmt=',.2f'))
+------+--------------+
| c1r1 | 14,502.05    |
+------+--------------+
| c1r2 |       105.00 |
+------+--------------+
```
Expected output:
```
+------+--------------+
| c1r1 |    14,502.05 |
+------+--------------+
| c1r2 |       105.00 |
+------+--------------+
```
This pull request changes the `_isnumber` function to recognize strings with commas, which without the commas parse as floats.
> Recognize numbers with comma separators

- tabulate.py
- test/test_input.py
Hi,
At the moment `_normalize_tabular_data` does not correctly recognise lists of UserDicts (or other dict-like objects) as it uses `isinstance(rows[0], dict)`. This patch switches the test to use `hasattr` instead and adds unit tests. 
Regards, Paul
> Support List of UserDicts (or other dict-like objects)

- tabulate.py
- test/test_api.py
`pretty` formatter should not, in my view, overwrite `stralign` and `numalign` if they are explicitly set by the caller. To achieve that, a small change in the handling of default arguments is required.
> allow to specify align in pretty formatter

- benchmark.py
Changes in `benchmark.py`.
Assigning `methods = methods` is redundant.
Module `platform` was imported with both `import` and `import from`, merged into one `import from`.
> benchmark: remove redundant assignment and double import

- tabulate.py
Reverts astanin/python-tabulate#51
This change has caused issues in Python 3 when floatfmt is not specified, but there's text with digits and comma in between.
I think this feature have to be re-implemented, and take care of the following use cases:
- if floatfmt with a grouping option ("_" or ",") is not specified, do not consider "123,456" to be a number
- if a grouping option is specified, parse numbers accordingly
Additional tests in test_output should be prepared.
> Revert "Recognize numbers with comma separators"

- README.md
- tabulate.py
- test/test_api.py
- test/test_internal.py
- test/test_output.py
- test/test_textwrapper.py
This address as submitted issue #90 that allows automatically word wrapping long text string. From an API standpoint, this is automatically enabled by simply specifying the maximum column width for a given column. I selected max column width instead of just column width to remove any confusion where a user might think that specifying `colwidth` might be setting a guaranteed size, which is not the behavior here (though I could see it as a possible future update?)
The "magic" here is a customized version of the `textwrap.TextWrapper` class to not use just `len` for strings and to also preserve ANSI color codes around wrapped lines. This is a non-trivial bit of code (even though heavily copy/pasted) with possible regression concerns, so I put it into a new test file to help tack this …
> Enable automatic word wrap based on desired maximum column width

- setup.py
Python 3.10 was released last week:
* https://discuss.python.org/t/python-3-10-0-is-now-available/10955
Also add `python_requires` to help pip.
Any thoughts about dropping support for EOL Python 2.7 and 3.5?
> Add support for Python 3.10

- tabulate.py
- test/test_internal.py
Fixes #130. It arrises as the function `_afterpoint` fails to recognize numbers with thousand separators. This happens because the function `_afterpoint` relies on the function `_isnumber` which relies on the built-in function `float.__init__` which fails on thousand-separated numbers. 
I did not change the function `_isnumber` as numbers such as "123,123" are to be aligned as plain text, resulting from the issue #110 and subsequent pulls and tests (`test/test_regression.py::test_string_with_comma_between_digits_without_floatfmt_grouping_option`). 
The solution is therefore implemented in the function `_afterpoint` by checking not only `_isnumber` but also a new function `__isnumber_with_thousands_separator` which validates floats or ints with thousand separators in [byte]string form. …
> fix afterpoint of numbers with thousand separators resulting in correct decimal alignment

- README.md
- tabulate.py
- test/test_output.py
* Add new `simple_grid` format, documentation and tests:
```
┌────────┬───────┐
│ item   │   qty │
├────────┼───────┤
│ spam   │    42 │
├────────┼───────┤
│ eggs   │   451 │
├────────┼───────┤
│ bacon  │     0 │
└────────┴───────┘
```
* Add new `rounded_grid` format, documentation and tests:
```
╭────────┬───────╮
│ item   │   qty │
├────────┼───────┤
│ spam   │    42 │
├────────┼───────┤
│ eggs   │   451 │
├────────┼───────┤
│ bacon  │     0 │
╰────────┴───────╯
```
* Add new `double_grid` format, documentation and tests:
```
╔════════╦═══════╗
║ item   ║   qty ║
╠════════╬═══════╣
║ spam   ║    42 ║
╠════════╬═══════╣
║ eggs   ║   451 ║
╠════════╬═══════╣
║ bacon  ║     0 ║
╚════════╩═══════╝
```
* Add new `outline` format, documentation and tests:
```
+--------+-------+
| item   | …
```
> Add new `rounded`/`simple`/`double`_`grid`/`outline` formats

- .pre-commit-config.yaml
- README.md
- appveyor.yml
- benchmark.py
- setup.py
- tabulate.py
- test/test_api.py
- test/test_cli.py
- test/test_input.py
- test/test_internal.py
- test/test_output.py
- test/test_regression.py
- test/test_textwrapper.py
- tox.ini
Python 2.7, 3.5 and 3.6 are EOL and no longer receiving security updates (or any updates) from the core Python team.
| cycle | latest |  release   |    eol     |
|:------|:-------|:----------:|:----------:|
| 3.10  | 3.10.1 | 2021-10-04 | 2026-10-04 |
| 3.9   | 3.9.9  | 2020-10-05 | 2025-10-05 |
| 3.8   | 3.8.12 | 2019-10-14 | 2024-10-14 |
| 3.7   | 3.7.12 | 2018-06-27 | 2023-06-27 |
| 3.6   | 3.6.15 | 2016-12-23 | 2021-12-23 |
| 3.5   | 3.5.10 | 2015-09-30 | 2020-09-13 |
| 2.7   | 2.7.18 | 2010-07-03 | 2020-01-01 |
https://endoflife.date/python
We can drop support for them, allowing us to use modern Python syntax, remove redundant compatibility code, reduce resource usage on the CI and make testing quicker.
> Drop support for EOL Python <= 3.6

- tabulate.py
- test/test_api.py
- test/test_output.py
Used a separate parameter to not break any usage/thoughts for maxcolwidth in the data. I can see how it may be useful to keep the two separate
> provide a parameter that allows for controlling header maxcolwidth

- README.md
- tabulate.py
- test/test_input.py
Thanks for your awesome library.
This can help with https://github.com/astanin/python-tabulate/issues/46.
Behavioural difference from that `asdict()` solution: `asdict()` will try to convert nested dataclasses to dicts as well (creating many copies), and producing different outputs:
```py
>>> from dataclasses import dataclass, asdict
>>> from tabulate import tabulate
>>> @dataclass
... class Mydata:
...     @dataclass
...     class Yolo:
...         x: int
...         y: int
...     name: str
...     yolo: Yolo
>>> d = [Mydata('origin', Mydata.Yolo(0, 0)), Mydata('v', Mydata.Yolo(22, -18))]
>>> print(tabulate(map(asdict, d), headers='keys'))
name    yolo
------  -------------------
origin  {'x': 0, 'y': 0}
v       {'x': 22, 'y': -18}
>>> print(tabulate(d, headers='keys'))
name    yolo …
```
> py37 dataclass support

- README.md
https://github.com/astanin/python-tabulate
Preview: https://github.com/hugovk/python-tabulate/tree/readme-formatting
> Add Markdown formatting for readability

- tabulate.py
- test/test_api.py
- test/test_internal.py
- test/test_output.py
This is to satisfy Issue #94: it allows setting a `rowalign` argument to `tabulate` that can be `top`, `bottom`, or `center` (with `top` being default if `None` is provided).
I replicated the table from the issue report to demonstrate:
```
import tabulate
from tabulate import Line, DataRow, TableFormat
mini_data = [
["r2", 0.7028],
["D'", 0.9229],
["abs_dist", 76864],
]
mini_table = tabulate.tabulate(mini_data, tablefmt="fancy_grid")
print(mini_table)
data = [
[mini_table, "rs3135388", "rs3129934"],
["chrom", "6", "6"],
["hg38_pos", "32445274", "32368418"],
["alleles", "A/G", "A/G"],
["alt_freq", "0.8797", "0.8579"]
]
result = tabulate.tabulate(data, tablefmt="fancy_grid", rowalign="bottom")
print(result)
```
gives:
```
╒═══════════════════════════╤═══════════╤═══════════╕
│ …
```
> Rows can specify top, bottom, or center alignment for their cell text

- README.md
- tabulate.py
- test/test_output.py
Introduces, as suggested in #155, 4 new styles:
* `heavy_grid`:
```
┏━━━━━━━━┳━━━━━━━┓
┃ item   ┃   qty ┃
┣━━━━━━━━╋━━━━━━━┫
┃ spam   ┃    42 ┃
┣━━━━━━━━╋━━━━━━━┫
┃ eggs   ┃   451 ┃
┣━━━━━━━━╋━━━━━━━┫
┃ bacon  ┃     0 ┃
┗━━━━━━━━┻━━━━━━━┛
```
* `mixed_grid`:
```
┍━━━━━━━━┯━━━━━━━┑
│ item   │   qty │
┝━━━━━━━━┿━━━━━━━┥
│ spam   │    42 │
├────────┼───────┤
│ eggs   │   451 │
├────────┼───────┤
│ bacon  │     0 │
┕━━━━━━━━┷━━━━━━━┙
```
* `heavy_outline`:
```
┏━━━━━━━━┳━━━━━━━┓
┃ item   ┃   qty ┃
┣━━━━━━━━╋━━━━━━━┫
┃ spam   ┃    42 ┃
┃ eggs   ┃   451 ┃
┃ bacon  ┃     0 ┃
┗━━━━━━━━┻━━━━━━━┛
```
* `mixed_outline`:
```
┍━━━━━━━━┯━━━━━━━┑
│ item   │   qty │
┝━━━━━━━━┿━━━━━━━┥
│ spam   │    42 │
│ eggs   │   451 │
│ bacon  │     0 │
┕━━━━━━━━┷━━━━━━━┙
```
Notes:
* I choose `heavy_` as a prefix …
> Implements `{heavy,mixed}_{grid,outline}`

- tabulate/__init__.py
All `*_outline` table formats have been broken since their inceptions:
```
>>> import tabulate
>>> tabulate.__version__
'0.8.8'
>>> print(tabulate([["a\nbb", "a\nbb\nccc\ndddd"]], tablefmt="fancy_outline"))
╒═╤═╕
│ a
bb  │ a
bb
ccc
dddd  │
╘═╧═╛
```
The correct rendering we are looking for is:
```
>>> print(tabulate([["a\nbb", "a\nbb\nccc\ndddd"]], tablefmt="fancy_outline"))
╒════╤══════╕
│ a  │ a    │
│ bb │ bb   │
│    │ ccc  │
│    │ dddd │
╘════╧══════╛
```
The problem is that we forgot to reference all these formats in the hard-coded [`tabulate.multiline_formats`](https://github.com/astanin/python-tabulate/blob/50ec140b4154307c285b4454a3ac305041de8d19/tabulate/__init__.py#L682-L712) variable.
Refs #80. Closes #203.
> Fix multiline folding of table formats rendering unseparated cells

- tabulate/__init__.py
- test/test_output.py
As stated on [wikipedia:WP:HTML5](https://en.wikipedia.org/wiki/Wikipedia:HTML_5), all instances of `align="center"` or `align="right"` must be replaced with `style="text-align: center;"` or `style="text-align: right;"`, respectively, to align text.
> Replace deprecated HTML

- appveyor.yml
- pyproject.toml
- tox.ini
Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) 🚀 
[![image](https://user-images.githubusercontent.com/1324225/198233993-5b79523b-370f-4316-a4be-9403c8209068.png)](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)
I didn't add 3.11 to AppVeyor as it doesn't support it yet: https://github.com/appveyor/ci/issues/3844
Instead I tested locally using tox (on macOS):
<details>
<summary>Details</summary>
```console
$ tox -e py311
.package create: /private/tmp/python-tabulate/.tox/.package
.package installdeps: setuptools>=61.2.0, setuptools_scm[toml]>=3.4.3
/private/tmp/python-tabulate/.tox/.package/lib/python3.11/site-packages/setuptools_scm/git.py:135: UserWarning: …
```
> Add support for Python 3.11

- tabulate/__init__.py
- test/test_output.py
The subject says it all.. 😉 
Tested:
```
lint: OK (6.63=setup[4.07]+cmd[2.56] seconds)
py37: OK (5.15=setup[3.97]+cmd[1.19] seconds)
py38: OK (4.83=setup[3.63]+cmd[1.20] seconds)
py39: OK (4.42=setup[3.28]+cmd[1.14] seconds)
py310: OK (4.77=setup[3.57]+cmd[1.20] seconds)
py311: OK (4.59=setup[3.34]+cmd[1.25] seconds)
congratulations :) (30.46 seconds)
```
> Fix bug/issue #231: SEPARATING_LINE feature doesn't work when the requested format pads columns

- tabulate/__init__.py
- test/common.py
I ran CodeQL scanning on the project and found the following 10 alerts.
I fixed 4 alerts and made this PR. Please review
> Fix code quality errors

- tabulate/__init__.py
- test/test_output.py
Resolved the problem with the `intfmt` argument.
Added tests for these changes.
Test results: `308 passed, 2 skipped in 1.10s`.
> Bug fix for issue #318 | `intfmt`: error for strings which contain integer values

- README.md
Fix #207 
* Change usage example to reconcile with the insertion-order preservation of dictionaries
* Document a long-existing feature of using a dictionary as the header for a list of dictionaries
> Fix #207. Update README: headers for dictionaries.

- tabulate/__init__.py
- test/test_output.py
To close #332, this PR adds a new table format "colon_grid" which is the same as the "grid" format but adds colons to the line below the header to indicate a column's alignment. This requires forcing left alignment on the data in the text output of tabulate. 
With this format, tabulate can create Pandoc-compatible tables with alignments.
Existing grid format:
```md
+------------+------------+------------+
| Column 1   | Column 2   | Column 3   |
+============+============+============+
| 1          | a          | 1.23       |
+------------+------------+------------+
| 2          | b          | 12.3       |
+------------+------------+------------+
| 3          | c          | 123        |
+------------+------------+------------+
```
Grid format using existing alignment functionality:
```md …
```
> Add table format "colon_grid"

- tabulate/__init__.py
The expected arguments in the command line utility do not match the help description. Furthermore, the long "--output" parameter was missing the following filename, and "--align" was later expected to be called "--colalign".
> Fix argument parsing of the command line utility

- tabulate.py
- test/test_output.py
Replace constant `PRESERVE_WHITESPACE` with optional argument `preserve_whitespace=False`
Resolves #37.
> preserve_whitespace as an argument to tabulate()

- README.md
- tabulate/__init__.py
This PR fixes issue [#214](https://github.com/astanin/python-tabulate/issues/214)
Issue:
- When you used a tuple for maxcolwidths, it caused an `TypeError` error.
PR:
- The original PR [#215](https://github.com/astanin/python-tabulate/pull/215) created by [Racerroar888](https://github.com/Racerroar888) was closed without merging, because of a merge conflict   
- This new PR includes the original code fix, a unit test, and fixes the merge conflict.
> Fix TypeError when using a tuple for maxcolwidths #214

- .github/workflows/lint.yml
- .github/workflows/tabulate.yml
- pyproject.toml
- test/test_regression.py
- tox.ini
The final Python 3.13 release candidate is out now! :rocket:
The Release Manager has issued a [call to action](https://discuss.python.org/t/python-3-13-0rc2-3-12-6-3-11-10-3-10-15-3-9-20-and-3-8-20-are-now-available/63161?u=hugovk]):
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.13 compatibilities during this phase, and where necessary publish Python 3.13 wheels on PyPI to be ready for the final release of 3.13.0. Any binary wheels built against Python 3.13.0rc2 will work with future versions of Python 3.13. As always, report any issues to [the Python bug tracker](https://github.com/python/cpython/issues).
> Add support for Python 3.13

- tabulate/__init__.py
- test/common.py
- test/test_textwrapper.py
In `tabulate._CustomTextWrap._handle_long_word`, ANSI escape codes may be broken in the middle, resulting wrongly formatted tables. That happens because the length of the string is checked in `while self._len(chunk[:i]) <= space_left:`, which may strip ANSI codes after they were broken by indexing into their middle.
To solve that, we instead calculate the length of the string without ANSI codes, then index into it: `while len(_strip_ansi(chunk)[:i]) <= space_left:`. That gives the amount of printable characters that should be included. Then we iterate through the escape codes present until we reach that many printable characters, and add the escape code lengths to figure out how much of the original string should be included. 
Tests included.
Test code:
```python
import tabulate …
```
> Fix column wrapping breaking ANSI escape codes (fixes #307)

- tabulate/__init__.py
- test/test_output.py
Allow missing (None) and empty ("") cells to be treated the same, for the purposes of deducing the column type.
This allows us to have empty cells (without the `missingval`), differentiated from missing cells (with the `missingval`), for columns generally containing numeric data, while retaining the correctly deduced column formatting.
Resolves #242
> Treat empty strings as generic for column type deduction, allow thousands separators

- README.md
- tabulate/__init__.py
The 'README.md' contains numerous examples and expected outputs, but these don't appear to be regularly tested.
I added the formatting necessary to run "doctest" on the README.md and test the expected outputs.  Mostly this was just adding a doctest-terminating blank line after the expected outputs.  However, several of the tests showed some differences in output.
Check that these are indeed now correct, and then this should be ready to merge.
I also added instructions on how to run doctest on the `README.md`.
> Correct README.md examples and outputs using doctest

- tabulate/__init__.py
- test/test_input.py
> Fix separating line with dataclasses

- README.md
This pull request addresses a minor spelling error in the `README.md` file.
Specifically, it corrects "diifference" to "difference" in the "ANSI support" section.
> fix(docs): Correct typo in ANSI support section

- tabulate/__init__.py
- test/test_output.py
In the `tabulate` library, the `github` format did not properly handle multiline text.  
If you passed tabulate data cells containing multiline text and used the `maxcolwidths` parameter to truncate text, the result was incorrect because the `github` format was not included in the list of formats that support multiline text processing.
The issue was that the `github` format was not added to the `multiline_formats` dictionary, which defines the formats that support multiline text.  
The solution was simple: just add `"github": "github"` to this dictionary.
After our fix, the `github` format now correctly processes multiline text, just like other supported formats such as `fancy_outline`.
> Fix multiline support for github format

- tabulate/__init__.py
- test/test_textwrapper.py
calling `_type` is incorrect here; the subsequent lines need a `str`. Also you can't reconstruct `None` with `type(None)(None)` anyway. This regressed in e8e3091d46966f462735f227d5ef4effdfaa0582
Fixes #305
> Fix handling "True"/"False" bool str and None
